services:
  postgresdb:
    image: postgres:18
    container_name: POSTGRESDB
    restart: always
    environment:
      POSTGRES_PASSWORD: aliengnss.
      POSTGRES_USER: aliengnss
      POSTGRES_DB: aliengnss
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
  pgadmin:
    image: dpage/pgadmin4
    container_name: cursos-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgresdb
volumes:
  pgdata: